/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class top_chendaye666_httpjni_JniUtil */

#ifndef _Included_top_chendaye666_httpjni_JniUtil
#define _Included_top_chendaye666_httpjni_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_chendaye666_httpjni_JniUtil
 * Method:    getNativeNum
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_top_chendaye666_httpjni_JniUtil_getNativeNum
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
