/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class top_chendaye666_equitruss_JniUtil */

#ifndef _Included_top_chendaye666_equitruss_JniUtil
#define _Included_top_chendaye666_equitruss_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_chendaye666_equitruss_JniUtil
 * Method:    getNativeQuery
 * Signature: (Ljava/lang/String;Ljava/lang/String;JLjava/lang/String;III)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_chendaye666_equitruss_JniUtil_getNativeQuery
  (JNIEnv *, jobject, jstring, jstring, jlong, jstring, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
