#
#	Global configuration for simrank
#
SIMRANK = simrank
INC1 = ./include
INC2 = ./include/sparsehash
INC3 = ./include/sparsehash/internal
GL = ./google
ARM = /usr/local/armadillo-10.2.1


UNAME := $(shell uname)

ifeq ($(UNAME), Linux)
  # Linux flags
  CC = g++
  CFLAGS += -ggdb
  CXXFLAGS += -std=c++11 -Wall
  CXXFLAGS += -O3 -DNDEBUG -fopenmp
  #CXXFLAGS += -fPIC
  # turn on for crash debugging, get symbols with <prog> 2>&1 | c++filt
  #CXXFLAGS += -g -rdynamic
  #CXXFLAGS += -ggdb
  # turn on for OpenMP
  CXXOPENMP =
  LDFLAGS +=
  LIBS += -lrt

else ifeq ($(UNAME), Darwin)
  # MacOS X flags
  CC = g++
  #CXXFLAGS +=  -std=c++11
  CXXFLAGS +=  -Wall -Wno-unknown-pragmas
  CXXFLAGS += -O3 -DNDEBUG
  # clang
  CLANG := $(shell g++ -v 2>&1 | grep clang | cut -d " " -f 2)
  ifneq ($(CLANG), LLVM)
    #CXXFLAGS += -fopenmp
  else
    CXXFLAGS += -DNOMP
    CXXOPENMP =
  endif
  LDFLAGS +=
  LIBS +=

else ifeq ($(shell uname -o), Cygwin)
  # Cygwin flags
  CC = g++
  CXXFLAGS += -Wall -D__STDC_LIMIT_MACROS
  CXXFLAGS += -O3 -DNDEBUG
  CXXOPENMP = -fopenmp
  LDFLAGS +=
  LIBS +=

endif

