/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class top_chendaye666_simrank_JniUtil */

#ifndef _Included_top_chendaye666_simrank_JniUtil
#define _Included_top_chendaye666_simrank_JniUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_chendaye666_simrank_JniUtil
 * Method:    getRank
 * Signature: (Ljava/lang/String;I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_chendaye666_simrank_JniUtil_getRank
  (JNIEnv *, jobject, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
