/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class top_chendaye666_neo4j_JniArray */

#ifndef _Included_top_chendaye666_neo4j_JniArray
#define _Included_top_chendaye666_neo4j_JniArray
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     top_chendaye666_neo4j_JniArray
 * Method:    testNativeString
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_top_chendaye666_neo4j_JniArray_testNativeString
  (JNIEnv *, jobject, jstring);

/*
 * Class:     top_chendaye666_neo4j_JniArray
 * Method:    testNativeArray
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_top_chendaye666_neo4j_JniArray_testNativeArray
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     top_chendaye666_neo4j_JniArray
 * Method:    testNativeArray2D
 * Signature: ([[I)[[I
 */
JNIEXPORT jobjectArray JNICALL Java_top_chendaye666_neo4j_JniArray_testNativeArray2D
  (JNIEnv *, jobject, jobjectArray);

/*
 * Class:     top_chendaye666_neo4j_JniArray
 * Method:    testNativeArrayListInt
 * Signature: (Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_top_chendaye666_neo4j_JniArray_testNativeArrayListInt
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
